// <auto-generated />

using GainsLab.Infrastructure.DB;
using GainsLab.Models.DataManagement.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GainsLab.Migrations
{
    [DbContext(typeof(GainLabSQLDBContext))]
    [Migration("20250705093330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("GainsLab.Models.DataManagement.DB.Model.DTOs.ComponentDescriptorDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("GainsLab.Models.DataManagement.DB.Model.DTOs.EquipmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescriptorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("GainsLab.Models.DataManagement.DB.Model.DTOs.EquipmentDTO", b =>
                {
                    b.HasOne("GainsLab.Models.DataManagement.DB.Model.DTOs.ComponentDescriptorDTO", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descriptor");
                });
#pragma warning restore 612, 618
        }
    }
}
