// <auto-generated />
using System;
using GainsLab.Infrastructure.DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GainsLab.Infrastructure.Migrations
{
    [DbContext(typeof(GainLabSQLDBContext))]
    [Migration("20251119140825_InitLocalSqlite")]
    partial class InitLocalSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.DescriptorDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("authority");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GUID")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc", "UpdatedSeq");

                    b.ToTable("descriptors", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.EquipmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DescriptorID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("updated_seq");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorID");

                    b.HasIndex("GUID")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc", "UpdatedSeq");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("authority");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DescriptorID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryDbId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorID");

                    b.HasIndex("GUID")
                        .IsUnique();

                    b.HasIndex("ParentCategoryDbId");

                    b.HasIndex("UpdatedAtUtc", "UpdatedSeq");

                    b.ToTable("movement_category", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MovementCategoryRelationDTO", b =>
                {
                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentCategoryId", "ChildCategoryId");

                    b.HasIndex("ChildCategoryId");

                    b.ToTable("movement_category_relations", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MuscleAntagonistDTO", b =>
                {
                    b.Property<int>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntagonistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MuscleId", "AntagonistId");

                    b.HasIndex("AntagonistId");

                    b.ToTable("muscle_antagonists", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MuscleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Authority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2)
                        .HasColumnName("authority");

                    b.Property<int>("BodySection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("body_section");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DescriptorID")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("updated_seq");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DescriptorID");

                    b.HasIndex("GUID")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc", "UpdatedSeq");

                    b.ToTable("muscles", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.Outbox.OutboxChangeDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("sent");

                    b.HasKey("Id");

                    b.HasIndex("Sent", "OccurredAt");

                    b.ToTable("outbox_changes", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.SyncState", b =>
                {
                    b.Property<string>("Partition")
                        .HasColumnType("TEXT");

                    b.Property<string>("CursorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastDeltaAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SeedCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SeedInProgress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpstreamSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Partition");

                    b.ToTable("SyncStates", (string)null);
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.EquipmentDTO", b =>
                {
                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.DescriptorDTO", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Descriptor");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", b =>
                {
                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.DescriptorDTO", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryDbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Descriptor");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MovementCategoryRelationDTO", b =>
                {
                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", "ChildCategory")
                        .WithMany("BaseCategoryLinks")
                        .HasForeignKey("ChildCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", "ParentCategory")
                        .WithMany("ChildCategoryLinks")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildCategory");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MuscleAntagonistDTO", b =>
                {
                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.MuscleDTO", "Antagonist")
                        .WithMany("Agonists")
                        .HasForeignKey("AntagonistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.MuscleDTO", "Muscle")
                        .WithMany("Antagonists")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antagonist");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MuscleDTO", b =>
                {
                    b.HasOne("GainsLab.Infrastructure.DB.DTOs.DescriptorDTO", "Descriptor")
                        .WithMany()
                        .HasForeignKey("DescriptorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Descriptor");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MovementCategoryDTO", b =>
                {
                    b.Navigation("BaseCategoryLinks");

                    b.Navigation("ChildCategoryLinks");
                });

            modelBuilder.Entity("GainsLab.Infrastructure.DB.DTOs.MuscleDTO", b =>
                {
                    b.Navigation("Agonists");

                    b.Navigation("Antagonists");
                });
#pragma warning restore 612, 618
        }
    }
}
